import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'About AIWritingCheck', description: 'Learn about our free AI content detection tool and how it works.' };

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-3xl font-extrabold text-gray-900 mb-8">About AIWritingCheck</h1>
      <div className="prose prose-lg prose-emerald max-w-none text-gray-700">
        <p>AIWritingCheck is a free AI writing style analyzer that helps you determine whether text was likely written by a human or generated by AI tools like ChatGPT, Claude, or Gemini.</p>
        <h2>How Our Analysis Works</h2>
        <p>We analyze four dimensions of writing style:</p>
        <ul>
          <li><strong>Perplexity:</strong> How predictable the word choices are. AI tends to use very common, expected words.</li>
          <li><strong>Burstiness:</strong> Variation in sentence length. Humans naturally vary between short and long sentences; AI tends to be uniform.</li>
          <li><strong>Repetition:</strong> Repeated phrases and structural patterns. AI often reuses similar constructions.</li>
          <li><strong>Vocabulary Diversity:</strong> The range of unique words used. AI text tends to rely on a narrower vocabulary.</li>
        </ul>
        <h2>Important Limitations</h2>
        <p>Our tool provides <strong>estimates only</strong>. No AI detector — including professional paid tools — is 100% accurate. Results should never be used as the sole basis for academic or professional decisions.</p>
        <h2>Privacy</h2>
        <p>All analysis happens in your browser using JavaScript. Your text is never sent to any server. We have zero access to the content you analyze.</p>
        <h2>Revenue Model</h2>
        <p>AIWritingCheck is free to use. We earn a small commission when you click through to recommended professional detection tools like Originality.ai or GPTZero.</p>
      </div>
    </div>
  );
}
