import Link from 'next/link';
import affiliates from '@/data/affiliates.json';

const features = [
  { icon: '⚡', title: 'Instant Analysis', desc: 'Get results in seconds. No waiting, no email — just paste and analyze.' },
  { icon: '🔒', title: '100% Private', desc: 'All analysis happens in your browser. Your text is never sent to any server.' },
  { icon: '🆓', title: 'Completely Free', desc: 'Analyze up to 1,000 words per check. No sign-up, no hidden fees.' },
  { icon: '📊', title: '4-Dimension Analysis', desc: 'Perplexity, burstiness, repetition, and vocabulary diversity scoring.' },
  { icon: '🔍', title: 'Sentence-Level Detail', desc: 'Every sentence is color-coded — see exactly which parts look AI-generated.' },
  { icon: '📱', title: 'Works Everywhere', desc: 'Use on desktop, tablet, or phone. No app download needed.' },
];

const useCases = [
  { icon: '👩‍🏫', title: 'For Teachers', desc: 'Check student essays and assignments for potential AI-generated content.' },
  { icon: '📝', title: 'For Editors', desc: 'Verify the authenticity of submitted articles and blog posts.' },
  { icon: '💼', title: 'For HR Teams', desc: 'Screen cover letters and writing samples during the hiring process.' },
  { icon: '✍️', title: 'For Writers', desc: 'Ensure your content won\'t be flagged as AI-generated by clients.' },
];

const faqs = [
  { q: 'How accurate is AIWritingCheck?', a: 'Our tool uses statistical analysis to estimate the likelihood of AI authorship. It provides a useful reference but is not 100% accurate. For definitive results, we recommend professional tools like Originality.ai or GPTZero.' },
  { q: 'Is my text stored or shared?', a: 'No. All analysis happens locally in your browser using JavaScript. Your text never leaves your device. We have zero access to anything you paste.' },
  { q: 'What AI models can it detect?', a: 'Our analysis looks for patterns common in text generated by ChatGPT, Claude, Gemini, and similar large language models. It analyzes writing style rather than identifying specific models.' },
  { q: 'Why is there a 1,000 word limit?', a: 'The free tool analyzes up to 1,000 words per check. For longer documents, you can split the text or use professional tools like Originality.ai which offer unlimited analysis.' },
  { q: 'Can I use the results as proof?', a: 'No. AI detection is probabilistic, not definitive. Our results should be used as one factor in your assessment, alongside other evidence. Never use any AI detector as the sole basis for academic or professional decisions.' },
];

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map((f) => ({
    '@type': 'Question',
    name: f.q,
    acceptedAnswer: { '@type': 'Answer', text: f.a },
  })),
};

export default function HomePage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      {/* Hero */}
      <section className="bg-gradient-to-br from-emerald-50 via-white to-emerald-50 py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 leading-tight">
            Is This Text Written by{' '}
            <span className="text-[--color-primary]">AI?</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-gray-600 max-w-2xl mx-auto">
            Free AI content detector — paste any text and instantly see if it was written by ChatGPT, Claude, or other AI.
            No sign-up. No data stored. 100% private.
          </p>
          <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/ai-detector" className="inline-block bg-[--color-primary] text-white px-8 py-4 rounded-xl text-lg font-semibold hover:bg-[--color-primary-dark] transition-colors shadow-lg shadow-emerald-200">
              Check Text Now — Free →
            </Link>
          </div>
          <div className="mt-8 flex flex-wrap justify-center gap-6 text-sm text-gray-500">
            <span>🆓 No sign-up</span>
            <span>🔒 100% private</span>
            <span>📊 4-dimension analysis</span>
            <span>⚡ Instant results</span>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl font-bold text-center text-gray-900">Who Uses AI Detection?</h2>
          <div className="mt-14 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {useCases.map((u) => (
              <div key={u.title} className="text-center">
                <div className="text-4xl mb-4">{u.icon}</div>
                <h3 className="text-lg font-semibold text-gray-900">{u.title}</h3>
                <p className="mt-2 text-gray-600 text-sm">{u.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl font-bold text-center text-gray-900">Why AIWritingCheck?</h2>
          <p className="mt-4 text-center text-gray-600 max-w-2xl mx-auto">Simple, fast, and transparent AI writing analysis.</p>
          <div className="mt-14 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((f) => (
              <div key={f.title} className="bg-white rounded-2xl p-8 hover:shadow-lg transition-shadow">
                <div className="text-4xl mb-4">{f.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900">{f.title}</h3>
                <p className="mt-2 text-gray-600 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl font-bold text-center text-gray-900">How It Works</h2>
          <div className="mt-14 grid grid-cols-1 md:grid-cols-4 gap-8">
            {[
              { n: '1', title: 'Paste Text', desc: 'Copy and paste the text you want to analyze (up to 1,000 words).' },
              { n: '2', title: 'Click Analyze', desc: 'Our algorithm examines writing patterns across 4 dimensions.' },
              { n: '3', title: 'View Results', desc: 'Get an AI probability score with sentence-level highlighting.' },
              { n: '4', title: 'Take Action', desc: 'Use the insights to make informed decisions about the content.' },
            ].map((s) => (
              <div key={s.n} className="text-center">
                <div className="w-14 h-14 mx-auto bg-[--color-primary] text-white rounded-full flex items-center justify-center text-xl font-bold">{s.n}</div>
                <h3 className="mt-4 text-lg font-semibold text-gray-900">{s.title}</h3>
                <p className="mt-2 text-gray-600 text-sm">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Affiliate */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl font-bold text-center text-gray-900">Need Professional-Grade Detection?</h2>
          <p className="mt-4 text-center text-gray-600 max-w-2xl mx-auto">For higher accuracy, batch processing, and advanced features, check out these trusted AI detection platforms.</p>
          <div className="mt-14 grid grid-cols-1 md:grid-cols-2 gap-8">
            {affiliates.map((p) => (
              <div key={p.slug} className="bg-white border border-gray-200 rounded-2xl p-8 hover:shadow-lg transition-shadow">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-xl font-bold text-gray-900">{p.name}</h3>
                  <span className="bg-emerald-100 text-[--color-primary] text-sm font-semibold px-3 py-1 rounded-full">★ {p.rating}</span>
                </div>
                <p className="text-gray-600 text-sm mb-4">{p.description}</p>
                <p className="text-[--color-primary] font-semibold mb-4">{p.price}</p>
                <div className="flex flex-wrap gap-2 mb-6">
                  {p.features.slice(0, 3).map((f) => (
                    <span key={f} className="bg-gray-100 text-gray-700 text-xs px-3 py-1 rounded-full">{f}</span>
                  ))}
                </div>
                <a href={`/go/${p.slug}`} target="_blank" rel="noopener noreferrer nofollow" className="inline-block bg-[--color-primary] text-white px-6 py-2.5 rounded-lg font-semibold hover:bg-[--color-primary-dark] transition-colors text-sm">
                  Try {p.name} →
                </a>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl sm:text-4xl font-bold text-center text-gray-900 mb-12">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq) => (
              <details key={faq.q} className="bg-gray-50 rounded-xl border border-gray-200 overflow-hidden">
                <summary className="flex items-center justify-between px-6 py-5 font-semibold text-gray-900 hover:bg-gray-100 transition-colors cursor-pointer">
                  {faq.q}
                  <svg className="faq-icon w-5 h-5 text-gray-500 transition-transform flex-shrink-0 ml-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </summary>
                <div className="px-6 pb-5 text-gray-600 leading-relaxed">{faq.a}</div>
              </details>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
